import React, { useRef } from 'react';
import { ArrowLeft, Download } from 'lucide-react';
import html2pdf from 'html2pdf.js';

const CampaignReport = ({ campaign, onBack }) => {
  const reportRef = useRef();

  // ROI Logic: ((Revenue - Budget) / Budget) * 100
  const budget = Number(campaign.budget) || 0;
  const revenue = Number(campaign.revenueGenerated) || 0;
  
  const roiValue = budget > 0 ? ((revenue - budget) / budget) * 100 : 0;

  // Determine Result Label
  let resultLabel = "BREAK EVEN";
  let resultClass = "text-secondary";

  if (roiValue > 0) {
    resultLabel = "PROFIT";
    resultClass = "text-success";
  } else if (roiValue < 0) {
    resultLabel = "LOSS";
    resultClass = "text-danger";
  }

  // PDF Download Handler
  const handleDownload = () => {
    const element = reportRef.current;
    const opt = {
      margin: 15,
      filename: `ROI_Report_${campaign.name}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };
    html2pdf().set(opt).from(element).save();
  };

  return (
    <div className="container py-4">
      {/* Action Header */}
      <div className="d-flex justify-content-between align-items-center mb-4 no-print">
        <button className="btn btn-outline-secondary d-flex align-items-center gap-2" onClick={onBack}>
          <ArrowLeft size={18} /> Back to Campaigns
        </button>
        <button className="btn btn-success d-flex align-items-center gap-2 shadow-sm" onClick={handleDownload}>
          <Download size={18} /> Download Report (PDF)
        </button>
      </div>

      {/* Report Content */}
      <div ref={reportRef} className="card p-5 border shadow-sm mx-auto" style={{ maxWidth: '800px', backgroundColor: '#fff', color: '#333' }}>
        <h2 className="text-center fw-bold mb-5 border-bottom pb-3">ROI Report</h2>
        
        <div className="report-details" style={{ fontSize: '1.1rem', lineHeight: '2.5' }}>
          <div className="row border-bottom py-2">
            <div className="col-5"><strong>Campaign Name</strong></div>
            <div className="col-7">: {campaign.name}</div>
          </div>
          
          <div className="row border-bottom py-2">
            <div className="col-5"><strong>Target Audience</strong></div>
            <div className="col-7">: {campaign.targetAudience}</div>
          </div>

          <div className="row border-bottom py-2">
            <div className="col-5"><strong>Campaign Duration</strong></div>
            <div className="col-7">: {campaign.startDate} to {campaign.endDate}</div>
          </div>

          <div className="row border-bottom py-2">
            <div className="col-5"><strong>Budget Invested</strong></div>
            <div className="col-7">: ₹{budget.toLocaleString('en-IN')}</div>
          </div>

          <div className="row border-bottom py-2">
            <div className="col-5"><strong>Revenue Generated</strong></div>
            <div className="col-7">: ₹{revenue.toLocaleString('en-IN')}</div>
          </div>

          <div className="row border-bottom py-2">
            <div className="col-5"><strong>Return on Investment</strong></div>
            <div className="col-7 fw-bold">: {roiValue.toFixed(1)}%</div>
          </div>

          <div className="row border-bottom py-2">
            <div className="col-5"><strong>Campaign Result</strong></div>
            <div className={`col-7 fw-bold ${resultClass}`}>: {resultLabel}</div>
          </div>
        </div>

        <div className="mt-5 text-center text-muted small">
          <p>Generated by ShopSphere Admin Panel • {new Date().toLocaleDateString()}</p>
        </div>
      </div>
    </div>
  );
};

export default CampaignReport;